---
- name: Ansible Setup  ----  Selected hosts only
  block:
    - name: Ansible Setup  ----  Install ansible (OS-codename {{ ansible_distribution_release }})
      ansible.builtin.apt:
        name:
          - ansible
        state: latest
        update_cache: true
    - name: Ansible  ----  Verify installation
      ansible.builtin.command: ansible --version
      register: ansible_version_output
    - name: Ansible  ----  Print version
      ansible.builtin.debug:
        msg: "{{ ansible_version_output.stdout }}"
    - name: Ansible  ----  Galaxy  ----  Install collections
      ansible.builtin.shell: ansible-galaxy collection install {{ item }}
      loop:
        - community.general
        - community.docker
      args:
        executable: /bin/bash
  # when: inventory_hostname == 'admin-pi.fritz.box'
